# Generated by Django 6.0.2 on 2026-02-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="star",
            field=models.IntegerField(default=1),
        ),
    ]
