# Generated by Django 6.0.2 on 2026-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_star"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="star",
            field=models.FloatField(default=1),
        ),
    ]
