# Generated by Django 6.0.2 on 2026-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="region",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["regionId"], name="regions_reg_regionI_2d1ed2_idx"
            ),
        ),
    ]
