# Generated by Django 6.0.2 on 2026-02-21 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
        ("regions", "0002_alter_region_options_region_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="regions.region",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["status"], name="complaints__status_7c8de0_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["category"], name="complaints__categor_8115a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["created_at"], name="complaints__created_805464_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["region"], name="complaints__region__3b944f_idx"
            ),
        ),
    ]
