# Generated by Django 6.0.2 on 2026-02-21 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_complaint_region_and_more"),
        ("regions", "0002_alter_region_options_region_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="regions.region",
            ),
        ),
    ]
