# Generated by Django 6.0.2 on 2026-02-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_alter_complaint_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="complaint_image",
            field=models.ImageField(blank=True, null=True, upload_to="complaints/"),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_image",
            field=models.ImageField(blank=True, null=True, upload_to="resolutions/"),
        ),
    ]
