# Generated by Django 6.0.2 on 2026-02-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_complaint_complaint_image_complaint_resolution_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="estimated_resolution_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="season_tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
